---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Import apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: Add repository
  apt_repository:
    repo: deb https://nginx.org/packages/mainline/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx

- name: Install nginx package
  apt:
    name: "nginx{% if nginx_install_full_package %}-full{% endif %}"

- name: Create config file for blocked IP addresses
  copy:
    force: false
    src: deny.conf
    dest: /etc/nginx/conf.d/deny.conf
    mode: 0644
    owner: root
    group: root

- name: Generate SSL dhparam if configured
  command:
    cmd: "openssl dhparam -out {{ nginx_ssl_dhparam }} 4096"
    creates: "{{ nginx_ssl_dhparam }}"
  when: nginx_ssl_dhparam is defined

- name: Create sites directory for storing different server configs
  file:
    path: /etc/nginx/sites/
    state: directory
    mode: 0755

- name: Set nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: /usr/sbin/nginx -t -c %s
  notify: Enable and start nginx

- name: Generate site config for each served domain
  template:
    src: site.conf.j2
    dest: "/etc/nginx/sites/{{ served_domain.identifier}}.conf"
  when: not served_domain.get('nginx_skip_server', False)
  notify: Enable and start nginx
  loop: "{{ nginx_served_domains }}"
  loop_control:
    loop_var: served_domain

- name: Place template PAM nginx file
  template:
    src: templates/pam_service_file.j2
    dest: "/etc/pam.d/{{ nginx_pam_service_name | mandatory }}"
  when: nginx_pam_rules is defined
  notify: Enable and start nginx

- name: Allow www-data to access shadow for PAM
  user:
    append: True
    groups: shadow
    name: www-data
  when: nginx_allow_shadow
  notify: Enable and start nginx

# stupid shell workaround needed since ansible still lacks an option to remove users from groups
# see also: https://github.com/ansible/ansible/issues/11024
- name: Forbid www-data shadow group access # noqa 305
  shell: deluser www-data shadow
  register: nginx_allow_shadow_remove
  when: not nginx_allow_shadow
  changed_when: nginx_allow_shadow_remove.rc != 6
  failed_when: nginx_allow_shadow_remove.rc != 6 and nginx_allow_shadow_remove.rc != 0

- name: Create script directory
  file:
    path: /etc/nginx/script.d
    state: directory

- name: Copy scripts
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/script.d/{{ item }}
    mode: 0755
    owner: root
    group: root
  with_items:
    - deny-ip.sh
